services:
  # redis:
  #   image: redis:latest
  #   container_name: redis-container
  #   ports:
  #     - "${REDIS_PORT}:6379"

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres-container
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  golang-api:
    build: .
    container_name: golang-api-container
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # depends_on:
    #   - redis
    #   - postgres
# networks:
#   app-network:
#     driver: bridge

# volumes:
#   postgres_data:
